source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

group :development, :test do
  # Гем для отладки. Вызов debugger() приводит к остановке и вызову binding.irb
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  # Гем для статического анализа и безопасности приложения
  gem 'brakeman'
  # Rubocop - линтер и статический анализатор
  gem 'rubocop'
  gem 'rubocop-rails'
end

